# Generated by Django 4.2.2 on 2025-08-05 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0002_client_owner_mailing_owner_message_owner_attempt"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={
                "ordering": ["name"],
                "permissions": [
                    ("can_view_all_clients", "Может просматривать всех клиентов")
                ],
                "verbose_name": "Клиент",
                "verbose_name_plural": "Клиенты",
            },
        ),
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "ordering": ["status"],
                "permissions": [
                    ("can_view_all_mailings", "Может просматривать все рассылки"),
                    ("can_disable_mailings", "Может отключать рассылки"),
                ],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
        migrations.AlterModelOptions(
            name="message",
            options={
                "ordering": ["topic"],
                "permissions": [
                    ("can_view_all_messages", "Может просматривать все сообщения")
                ],
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
            },
        ),
        migrations.AlterField(
            model_name="attempt",
            name="attempt_time",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Время попытки"),
        ),
    ]
